version: '3.9'

services:
  stage-etl:
    build: .
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 10
        window: 120s
    container_name: stage-etl
    environment:
      DB_POSTGRES_HOST: db_potok
    env_file:
      - .env
    networks:
      - db-net
    entrypoint: ['python', 'src/stage.py']


networks:
  db-net:
    name: db-net
    external: true